feat&build: 스토리북 세팅
dddstudy/ddd-web pull request #4
Opened 2024-10-01 08:50 UTC by dkkim0122

### 작업 내용
* 프로젝트의 컴포넌트 디자인이 먼저 진행되어, 디자이너 및 기획 파트와의 협업을 원활히 하기 위해 스토리북을 세팅합니다.
* Chromatic을 사용하여 배포하고, develop과 main 브랜치에 push 시 자동으로 배포되도록 깃헙 액션을 추가합니다.
  * [배포 주소](https://www.chromatic.com/library?appId=66fb93d4f124a3b3c23717f6)

### 참고사항
* 지금은 예시 컴포넌트밖에 없어서.. 컴포넌트 작성하면 하나씩 넣도록 해요
* 컴포넌트 작성 시
  * components 하위에 각 컴포넌트 폴더 생성
  * 폴더 내 .tsx 파일과 .stories.tsx 작성

2024-10-05 12:11 UTC, Gn0lee requested changes
package.json의 스크립트를 수정하면 더 좋을 것 같습니다~

2024-10-08 09:54 UTC, dkkim0122 commented on .github/workflows/chromatic.yml
> +        run: npm run ci
음 단계 나눠서 진행하는 게 더 맞겠네요. 수정하겠습니다~

2024-10-08 09:56 UTC, dkkim0122 commented on package.json
> +    "chromatic": "npx chromatic --project-token=chpt_737ac8e71cf21ff",
chromatic 말씀하시는 거죠? 같은 토큰이긴 합니다. 혹시 수동으로 배포할 일이 있을까 해서 넣어두긴 했는데, 저 토큰 값이 노출되는 게 저도 좀 꺼려지긴 하네요.. 저거 그냥 삭제하고 깃헙 액션 통해서만 가능하도록 변경할게요

2024-10-08 12:53 UTC, Gn0lee approved these changes
LGTM 👍

2024-10-08 12:56 UTC, merged